# Generated by Django 5.2.18 on 2026-10-08 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono_whatsapp', models.CharField(max_length=20)),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=2)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.centro')),
            ],
            options={
                'db_table': 'clienta',
            },
        ),
        migrations.CreateModel(
            name='FichaEstetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cutis', models.CharField(blank=True, max_length=80)),
                ('alergias', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('clienta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_estetica', to='clientas.clienta')),
            ],
            options={
                'db_table': 'ficha_estetica',
            },
        ),
        migrations.AddConstraint(
            model_name='clienta',
            constraint=models.UniqueConstraint(fields=('centro', 'telefono_whatsapp'), name='clienta_tel_unico_por_centro'),
        ),
    ]
