# Generated by Django 5.2.17 on 2026-10-08 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_cita_recordatorio_cita_cita_centro__dd9cb0_idx_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SENA', 'Seña'), ('SALDO', 'Saldo'), ('REEMBOLSO', 'Reembolso')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('FALLIDO', 'Fallido'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=12)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pasarela', models.CharField(blank=True, max_length=30)),
                ('referencia', models.CharField(blank=True, help_text='ID de la transacción en la pasarela', max_length=80, null=True, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.centro')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='agenda.cita')),
            ],
            options={
                'db_table': 'pago',
                'ordering': ['-creado_en'],
            },
        ),
    ]
