# Generated by Django 5.2.18 on 2026-10-08 03:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.centro')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_profesional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profesional',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('duracion_minutos', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('porcentaje_sena', models.PositiveSmallIntegerField(default=30, help_text='% del precio cobrado como seña', validators=[django.core.validators.MaxValueValidator(100)])),
                ('activo', models.BooleanField(default=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.centro')),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Cabina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('activa', models.BooleanField(default=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.centro')),
            ],
            options={
                'db_table': 'cabina',
                'constraints': [models.UniqueConstraint(fields=('centro', 'nombre'), name='cabina_nombre_unico')],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField()),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='agenda.profesional')),
            ],
            options={
                'db_table': 'disponibilidad_profesional',
                'constraints': [models.CheckConstraint(condition=models.Q(('dia_semana__lte', 6)), name='disp_dia_valido'), models.CheckConstraint(condition=models.Q(('hora_hasta__gt', models.F('hora_desde'))), name='disp_horas_validas')],
            },
        ),
        migrations.CreateModel(
            name='BloqueoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=150)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.centro')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='agenda.profesional')),
            ],
            options={
                'db_table': 'bloqueo_agenda',
                'constraints': [models.CheckConstraint(condition=models.Q(('fin__gt', models.F('inicio'))), name='bloqueo_rango_valido')],
            },
        ),
    ]
