# Generated by Django 5.2.17 on 2026-10-08 23:04

import apps.agenda.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('clientas', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada'), ('NO_ASISTIO', 'No asistió')], default='PENDIENTE', max_length=12)),
                ('origen', models.CharField(choices=[('NORMAL', 'Normal'), ('REASIGNACION', 'Reasignación exprés')], default='NORMAL', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cabina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='agenda.cabina')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.centro')),
                ('clienta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='clientas.clienta')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='agenda.profesional')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='agenda.servicio')),
            ],
            options={
                'db_table': 'cita',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('H48', '48 horas antes'), ('H24', '24 horas antes')], max_length=3)),
                ('programado_para', models.DateTimeField()),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.CharField(choices=[('SIN_RESPUESTA', 'Sin respuesta'), ('CONFIRMA', 'Confirma'), ('CANCELA', 'Cancela')], default='SIN_RESPUESTA', max_length=14)),
                ('wa_message_id', models.CharField(blank=True, max_length=120)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='agenda.cita')),
            ],
            options={
                'db_table': 'recordatorio',
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['centro', 'hora_inicio'], name='cita_centro__dd9cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['cabina', 'hora_inicio'], name='cita_cabina__b402dd_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['profesional', 'hora_inicio'], name='cita_profesi_bb23af_idx'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='cita_rango_valido'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'CONFIRMADA'])), expressions=[(apps.agenda.models.TsTzRange('hora_inicio', 'hora_fin', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('cabina', '=')], name='sin_cruce_cabina'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'CONFIRMADA'])), expressions=[(apps.agenda.models.TsTzRange('hora_inicio', 'hora_fin', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('profesional', '=')], name='sin_cruce_profesional'),
        ),
        migrations.AddConstraint(
            model_name='recordatorio',
            constraint=models.UniqueConstraint(fields=('cita', 'tipo'), name='recordatorio_unico_por_tipo'),
        ),
    ]
