# Generated by Django 5.2.17 on 2026-10-08 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0002_cita_recordatorio_cita_cita_centro__dd9cb0_idx_and_more'),
        ('clientas', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_deseada', models.DateField()),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.centro')),
                ('clienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esperas', to='clientas.clienta')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esperas', to='agenda.servicio')),
            ],
            options={
                'db_table': 'lista_espera',
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='OfertaReasignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('enviada_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida')], default='PENDIENTE', max_length=10)),
                ('respondida_en', models.DateTimeField(blank=True, null=True)),
                ('cita_liberada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='agenda.cita')),
                ('espera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='reasignacion.listaespera')),
            ],
            options={
                'db_table': 'oferta_reasignacion',
                'ordering': ['cita_liberada', 'orden'],
            },
        ),
        migrations.AddIndex(
            model_name='listaespera',
            index=models.Index(fields=['servicio', 'fecha_deseada', 'estado'], name='lista_esper_servici_5e93d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='ofertareasignacion',
            constraint=models.UniqueConstraint(fields=('cita_liberada', 'espera'), name='oferta_unica_por_espera'),
        ),
    ]
